// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceServer.Data;

#nullable disable

namespace ResourceServer.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20240812063923_FileStream")]
    partial class FileStream
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResourceServer.Models.ResourceFile", b =>
                {
                    b.Property<Guid>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("stream_id");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("creation_time");

                    b.Property<byte[]>("FileStream")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("file_stream");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_type")
                        .HasComputedColumnSql("RIGHT(Name, CHARINDEX('.', REVERSE(Name)) - 1)", true);

                    b.Property<DateTimeOffset>("LastAccessTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_access_time");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_write_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("StreamId");

                    b.ToTable("ResourceFiles", null, t =>
                        {
                            t.HasComment("таблиця для файлів");
                        });
                });

            modelBuilder.Entity("ResourceServer.Models.ResourceFileConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdResourceFile")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID_ResourceFile");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdResourceFile");

                    b.ToTable("ResourceFileConnection", null, t =>
                        {
                            t.HasComment("таблиця для зв'язку файлів");
                        });
                });

            modelBuilder.Entity("ResourceServer.Models.ResourceFileConnection", b =>
                {
                    b.HasOne("ResourceServer.Models.ResourceFile", "IdResourceFileNavigation")
                        .WithMany("ResourceFileConnections")
                        .HasForeignKey("IdResourceFile")
                        .IsRequired()
                        .HasConstraintName("FK_Resource_FileConnections_ResourceFile");

                    b.Navigation("IdResourceFileNavigation");
                });

            modelBuilder.Entity("ResourceServer.Models.ResourceFile", b =>
                {
                    b.Navigation("ResourceFileConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
